import Head from 'next/head'
import System from "../components/System"
import Navbar from "../components/Navbar"
import { useSession, getSession } from "next-auth/react"
import { serverSideRedirect } from '@/utils/server-side-redirect'

export default function SystemPage(){
  return(
    <>
      <Head>
        <title>NextAuth | System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <System />
    </>
  )
}

export async function getServerSideProps(context){
  const { data: session } = await getSession(context)
  
  if(!session){
    console.log('REDIRECT')
    return serverSideRedirect(context)
  }

  return {
    props: {}
  }
}