import Head from 'next/head'
import System from "../components/System"
import Navbar from "../components/Navbar"
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { useSession } from 'next-auth/react'

export default function SystemPage(){
  const {status} = useSession()
  const Router = useRouter()
  useEffect(()=>{
    if(status === 'unauthenticated'){
        Router.push("/login")
      }
    },[status])
  return(
    <>
      <Head>
        <title>System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <System />
    </>
  )
}