import Head from 'next/head'
import System from "../components/System"
import Navbar from "../components/Navbar"
import { useSession, getSession } from "next-auth/react"
import { serverSideRedirect } from '@/utils/server-side-redirect'
import { frontEndRedirect } from '@/utils/front-end-redirect'

export default function SystemPage(){
  const { data: session, status } = useSession()

  if(!session && !status) {
    return frontEndRedirect()
  }

  if (status === "loading") {
    return <p>Loading...</p>
  }
  
  // if (typeof window !== 'undefined' && status) return null
  
  if(!session){
    return frontEndRedirect()
  }
  return(
    <>
      <Head>
        <title>NextAuth | System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {session &&
      <System name={session.user.name} username={session.user.username}/>
      }
    </>
  )
}

export async function getServerSideProps(context){
  const session = await getSession(context)
  
  if(!session){
    return serverSideRedirect(context)
  }

  return {
    props: {}
  }
}